FROM golang:1.24.4-alpine3.22 AS builder
WORKDIR /go/src/github.com/osrg/gobgp
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w -buildid=" -o /go/bin/gobgpd ./cmd/gobgpd
RUN CGO_ENABLED=0 go build -ldflags="-s -w -buildid=" -o /go/bin/gobgp ./cmd/gobgp

# FROM osrg/quagga
# COPY --from=builder /go/bin/gobgpd /go/bin/gobgpd
# COPY --from=builder /go/bin/gobgp /go/bin/gobgp
# ENV PATH="/go/bin:${PATH}"
# CMD ["/go/bin/gobgpd"]